[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qe"
version = "0.1.0"
dependencies = [
    "lxml>=4.9.0",
    "click>=8.1.0",
    "adb-shell>=0.4.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.0.0"]